# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9830d7628fac1491170ccee2653ecddc7ffd6649f9ec58212e237843fbf38fc56e42fd41caf56649b7e77e8c9bd4127d334a828d38f2d28775aeec0b953fdb01

test:
  secret_key_base: 09cf547d061b452ce1c3b4d75175c1aa845adc74550e0924915c4f6e8a714ecdd59a3a7e16036b1c4b68f86e87bd48a40ce7a3493d96ec7c96f296fcee037e1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
